### ISSUE TITLE
Adding functionality  to user model

### ISSUE THREAD

**Issue by rawadabu** [redhat-beyond/Smarticle#25]
- [x] Adding functionality to user model[create/delete/get].
- [x] Adding new file called test_user.py for testing user functions.
- [x] Added tests/generate_objects.py to generate all the objects we need.
- [ ] Adding user articles by likes/views.

**Comment by Shalevro2** [comment]
I think when we add functionality to a model we need also to add tests.
Maybe you can add at the issue description that you gonna add some test to this model.

**Comment by rawadabu** [comment]
@Shalevro2 Yes with test_user.py file you meant right?
Otherwise django-pytest CI won't pass

**Comment by Shalevro2** [comment]
> @Shalevro2 Yes with test_user.py file you meant right? Otherwise django-pytest CI won't pass

Yes, think so.
