### ISSUE TITLE
Adding fail conditions to test_user.py file

### ISSUE THREAD

**Issue by rawadabu** [redhat-beyond/Smarticle#49]
- To add test function that test the bad cases.

**Comment by Shalevro2** [comment]
Maybe we can to splite this issue.
Consider to create issue per test file, then we can make a smaller PR.
@rawadabu WDYT?

**Comment by rawadabu** [comment]
@Shalevro2 Agreed, would be easier for merging with no conflicts, I will change this issue to test_user file only

**Comment by Shalevro2** [comment]
> @Shalevro2 Agreed, would be easier for merging with no conflicts, I will change this issue to test_user file only

Great!
