### ISSUE TITLE
Create a create-article feature

### ISSUE THREAD

**Issue by Shalevro2** [redhat-beyond/Smarticle#58]
- [x] Create a new folder under `\Smarticle\projboard\templates`, there will be located the html parts of this feature
- [x] Create the html parts 
- [x] Add to the `\Smarticle\projboard\views.py` file a function to render this html part
- [x] To create a new route, we add to the `Smarticle\finalProject_g4\urls.py` file a new path
- [x] Add a test file that test the changes you add
- [x] You can read more about the adding features [here](https://drive.google.com/file/d/11i6Skxw5ch1dZCnGj5ldG7DFBUCkSucV/view) (pages 45-48, task-7)

**Comment by rawadabu** [comment]
@Shalevro2 Lets make a branch `create-article-feature` so we could work together on our tasks, wdyt?

**Comment by Shalevro2** [comment]
> @Shalevro2 Lets make a branch `create-article-feature` so we could work together on our tasks, wdyt?

SGTM
