### ISSUE TITLE
Create a my-articles feature

### ISSUE THREAD

**Issue by yaelnoyman1** [redhat-beyond/Smarticle#77]
- [x] Create a new folder under \Smarticle\projboard\templates, there will be located the html parts of this feature
 - [x]  Create the html file and css
 - [x] Add to the \Smarticle\projboard\views.py file a function to render this html part
 - [x] Add to the Smarticle\finalProject_g4\urls.py file a new path to create a new route
 - [x] Add a test file that test the changes you add

**Comment by Shalevro2** [comment]
Please change the title to `Create a my-articles feature`
